import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NextAuthProvider from '@/Provider'
import ServerNav from '@/components/NavComps/ServerNav'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Sangkap',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className="bg-white min-h-screen lg:w-4/5 mx-auto">
        <NextAuthProvider>
          <div className='relative'>
            <header>
              <ServerNav />
            </header>
            {children}
          </div>
        </NextAuthProvider>
      </body>
    </html>
  )
}
