import type { Metadata } from 'next'
import NextAuthProvider from '@/Provider'
import ServerNav from '@/components/NavComps/ServerNav'


export const metadata: Metadata = {
    title: 'Sangkap',
    description: 'Generated by create next app',
}

export default async function HomeLayout({
    children,
}: {
    children: React.ReactNode
}) {

    return (
        <section>
            {/* <body className="bg-white min-h-screen"> */}
            <NextAuthProvider>
                <div className='lg:w-3/4 lg:mx-auto lg:border relative'>
                    <div>
                        <ServerNav />
                    </div>
                    {children}
                </div>
            </NextAuthProvider>
            {/* </body> */}
        </section>
    )
}