import NextAuthProvider from "@/Provider"

export const metadata = {
  title: 'Login page',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <section lang="en">
      <NextAuthProvider>
        <div>
          {children}
        </div>
      </NextAuthProvider>
    </section>
  )
}
